-- AlterTable
ALTER TABLE "PlaceDetail" ALTER COLUMN "basicInfo" SET DATA TYPE TEXT,
ALTER COLUMN "findway" SET DATA TYPE TEXT,
ALTER COLUMN "photo" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "address" SET DATA TYPE TEXT;
